name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: A clear and concise description of what the bug is.
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: Create a minimal reproduction of the problem in a new repository and link to it here.
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Steps to reproduce the behavior.
      value: |
        1. Import the version '...'
        2. Create a new instance of the class '...'
        3. Call the method '...'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: If applicable, add logs to help explain your problem.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: "Affected versions"
      description: What version(s) of Step Functions are affected by this issue? (You can select multiple versions).
      multiple: true
      options:
        - 1.0.0
    validations:
      required: true
  - type: dropdown
    id: java
    attributes:
      label: "Java bersions"
      description: What version(s) of Java are affected by this issue? (You can select multiple versions).
      multiple: true
      options:
        - 8
        - 11
        - 17
        - 19
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: "Contact details"
      description: How can we contact you if we need more info?
      placeholder: "ex. Discord: USERNAME#0000 or Email: username@example.com"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Terms and Conditions"
      description: Please read and confirm the below terms and conditions.
      options:
        - label: >
            I have searched the [issue tracker](https://github.com/Koralix-Studios/step-functions/issues)
            for an issue that matches the one I want to file, without success.
          required: true
        - label: >
            I have read the [README](https://github.com/Koralix-Studios/step-functions/blob/master/README.md) and
            [wiki](https://github.com/Koralix-Studios/step-functions/wiki) and I am sure that my issue is not related
            to a lack of understanding.
          required: true
        - label: >
            I agree to follow this project's
            [Code of Conduct](https://github.com/Koralix-Studios/step-functions/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: >
            I have read the
            [CONTRIBUTING](https://github.com/Koralix-Studios/step-functions/blob/master/.github/CONTRIBUTING.md) guide
            and I am following the recommendations to file a good issue.
          required: true